CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS locations (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    lat FLOAT NOT NULL,
    lon FLOAT NOT NULL
);

CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    annotation VARCHAR NOT NULL,
    category_id BIGINT NOT NULL REFERENCES categories (id) ON DELETE CASCADE,
    confirmed_requests INT,
    created_on TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    description VARCHAR NOT NULL,
    event_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    initiator_id BIGINT NOT NULL,
    initiator_name VARCHAR NOT NULL,
    location_id BIGINT NOT NULL REFERENCES locations (id) ON DELETE CASCADE,
    paid BOOL,
    participant_limit INT,
    published_on TIMESTAMP WITHOUT TIME ZONE,
    request_moderation BOOL,
    title VARCHAR NOT NULL,
    state VARCHAR NOT NULL,
    views BIGINT
);

CREATE TABLE IF NOT EXISTS compilations (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    pinned BOOL NOT NULL,
    title VARCHAR NOT NULL
);

create table if not exists compilations_events (
    events_id BIGINT NOT NULL REFERENCES events (id) ON DELETE CASCADE,
    compilation_id BIGINT NOT NULL REFERENCES compilations (id) ON DELETE CASCADE,
    PRIMARY KEY (events_id, compilation_id)
);

CREATE TABLE IF NOT EXISTS comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  text VARCHAR(255) NOT NULL,
  event_id BIGINT,
  author_id BIGINT,
  author_name VARCHAR NOT NULL,
  created TIMESTAMP NOT NULL,
  CONSTRAINT pk_comment PRIMARY KEY (id),
  CONSTRAINT fk_item_id FOREIGN KEY (event_id) references events (id) ON DELETE CASCADE
);